### ISSUE TITLE
No main attribute in manifest

### ISSUE THREAD

**Issue by SimonMarynissen** [java-opengl-labs/learn-OpenGL#2]
When trying to run the jar file, it complains about having no main attribute in the manifest. After diving in the jar, the manifest is only one line:
Manifest-Version: 1.0

**Comment by elect86** [comment]
Uhm, does it make sense to have a main class?

This project shall just be cloned and run..

How are you using it?

**Comment by SimonMarynissen** [comment]
Then how do you run it? I thought you had to run the jar file...

**Comment by elect86** [comment]
You open your IDE, clone the project, and then run each lesson singularly

Do you know how to do that?

**Comment by SimonMarynissen** [comment]
Yeah, I can do that, it wasn't really clear from the read-me. :)

**Comment by elect86** [comment]
Thanks for the input, I'll improve it

**Comment by elect86** [comment]
Simon, if the readme is clear, you can close this issue
